# Copyright The Conforma Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
rules: # error | warning | off
  no-duplicate-param: error
  no-invalid-name: error
  no-invalid-param-type: error
  no-pipeline-missing-parameters: error
  no-pipeline-missing-task: error
  no-pipeline-task-cycle: error
  no-extra-param: error
  no-missing-workspace: error
  no-undefined-result: error
  no-missing-param: error
  no-duplicate-resource: error
  no-resourceversion: error
  no-duplicate-env: error
  no-undefined-volume: error
  no-latest-image: warning
  prefer-beta: warning
  prefer-kebab-case: warning
  no-unused-param: warning
  no-missing-resource: error
  no-undefined-param: error
  prefer-when-expression: warning
  no-deprecated-resource: warning
  no-missing-hashbang: warning
